<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_drawing</name>
   <tag></tag>
   <elementGuidId>dd6051d1-5745-4f74-83eb-33be61f54b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.docssharedWizToggleLabeledContainer.ajBQVb.N2RpBe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mG61Hd']/div[2]/div/div[2]/div[3]/div/div/div[2]/div/div/span/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c5b11063-506a-415f-affd-c2b93760f118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>i13</value>
      <webElementGuid>4549cafa-ddef-4845-8c2b-bafca7d07e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>docssharedWizToggleLabeledContainer ajBQVb N2RpBe</value>
      <webElementGuid>3e1a8bd0-93d8-4d93-b7df-7afbfd2d8863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>drawing</value>
      <webElementGuid>506dc401-cfeb-497d-9470-00fda0257090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mG61Hd&quot;)/div[@class=&quot;RH5hzf RLS9Fe&quot;]/div[@class=&quot;lrKTG&quot;]/div[@class=&quot;o3Dpx&quot;]/div[@class=&quot;Qr7Oae&quot;]/div[1]/div[@class=&quot;geS5n&quot;]/div[@class=&quot;oyXaNc&quot;]/div[1]/div[@class=&quot;lLfZXe fnxRtf cNDBpf&quot;]/span[@class=&quot;H2Gmcc tyNBNd&quot;]/div[@class=&quot;SG0AAe&quot;]/div[@class=&quot;nWQGrd zwllIb&quot;]/label[@class=&quot;docssharedWizToggleLabeledContainer ajBQVb N2RpBe&quot;]</value>
      <webElementGuid>2e69e15f-3306-4bcb-8fba-2657eefb85a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mG61Hd']/div[2]/div/div[2]/div[3]/div/div/div[2]/div/div/span/div/div/label</value>
      <webElementGuid>c4334851-781d-4fda-82a8-7e0ebd80835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::label[1]</value>
      <webElementGuid>49371d9b-5482-413f-80ee-9100651f2ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='playing music'])[1]/preceding::label[1]</value>
      <webElementGuid>7de20903-f246-4858-88f1-eac1701ae84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>40dc041f-f06d-4d0f-83ef-b7e07f456aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'drawing' or . = 'drawing')]</value>
      <webElementGuid>20007156-1815-4419-9f42-60b423dbbf75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
